# Generated by Django 5.2.4 on 2025-08-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(upload_to='products/')),
                ('playback_badge', models.CharField(blank=True, max_length=100)),
                ('rating', models.FloatField(default=0.0)),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.CharField(max_length=50)),
            ],
        ),
    ]
