# Generated by Django 5.2.4 on 2025-08-05 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boAt_web', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='AddProduct',
        ),
    ]
