# Generated by Django 5.2.4 on 2025-08-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boAt_web', '0003_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='price',
            field=models.FloatField(),
        ),
    ]
