# Generated by Django 5.2.4 on 2025-08-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boAt_web', '0008_rename_full_name_order_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tax',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
